Features/type checking
electrumsv/electrumsv-sdk pull request #107
Opened 2021-07-06 00:13 UTC by AustEcon

2021-07-06 00:15 UTC, rt121212121 commented on contrib/run_pylint.bat
> +py -3.7 -m pip install pylint
Why is this 3.7?

2021-07-06 01:20 UTC, AustEcon commented on contrib/run_pylint.bat
> +py -3.7 -m pip install pylint
Because my dev computer has an issue where I can't use pylint with version 3.9...

2021-07-07 02:35 UTC, AustEcon commented on contrib/run_pylint.bat
> +py -3.7 -m pip install pylint
As already discussed - this issue is now resolved by manually upgrading my version of pip-api.

The exact issue I was facing is detailed here:
https://github.com/di/pip-api/issues/68

2021-07-07 03:41 UTC, rt121212121 requested changes

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/argparsing.py
>          self.node_args = None
This needs a type.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/argparsing.py
>          self.config = None
This needs a type.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/argparsing.py
> +    def add_node_argparser(self, namespaces) -> ArgumentParser:
args need typing, for all methods that take `namespaces` or `top_level_parser`.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/builtin_components/node/node.py
> +            rpcport = component_dict.get("metadata", {}).get("rpcport")
Is it possible to use a `TypedDict` for `component_dict`. This would ensure that the rpcport value woud not be unknown for example.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/builtin_components/status_monitor/server_app.py
> +    async def manual_heartbeat(self, ws, ws_id):
Arguments need typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/commands.py
> +def _validate_network(network: str, component_type) -> None:
`component_type` is untyped.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/components.py
>          metadata: Optional[dict] = None,
Can `dict` here be a `TypedDict` class?

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/components.py
> +    def to_dict(self) -> Dict:
Can `Dict` here be a `TypedDict`

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/components.py
> +    def from_dict(cls, component_dict: Dict) -> "Component":
`component_dict`  a `TypedDict`?

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/config.py
> +    cli_extension_args: dict = {}
`TypedDict`

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/controller.py
>          self.component_info = None
`component_info` is missing a type.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/plugin_tools.py
> +class NETWORKS:
Duplicated from `constants.py`?

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/plugin_tools.py
> +    def call_for_component_id_or_type(self, component_name: str, callable: Callable) -> None:
Is there any way to type the `Callable` with argument and return types?

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def cast_str_int_args_to_int(node_args: List) -> List:
`List` needs contents typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def get_directory_name(component__file__) -> str:
Argument needs typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def get_parent_and_child_pids(parent_pid) -> Optional[List[int]]:
Argument needs typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def sigint(pid) -> None:
Argument needs typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def sigkill(parent_pid) -> None:
Argument needs typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def kill_by_pid(pid: int) -> None:
Argument needs typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def kill_process(component_dict: Dict) -> None:
`component_dict` should be a `TypedDict` subclass.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def is_default_component_id(component_name, component_id) -> bool:
Arguments need typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def tail(logfile) -> None:
Argument needs typing.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def update_status_monitor(pid: int, component_state: Optional[ComponentState], id: str,
`metadata` needs specific `Dict` typing, whether `TypedDict` or other.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def spawn_background_supervised(command: str, env_vars: Dict, id: str, component_name:
This can't be right, is it being tested? `src: Path=None` Or does the typing expand the `Path` to `Optional[Path]`?

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +def spawn_new_terminal(command: str, env_vars: Dict, id: str, component_name:
All `env_vars` usage should be specific `Dict` types, likely `TypedVar`.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +    component_dict: Dict = component_store.component_status_data_by_id(node_id)
All `component_dict` should be `TypedDict` subclass.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/utils.py
> +        metadata: Dict = component_dict.get("metadata", {})
All `metadata` should be `TypedDict` subclass.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/validate_cli_args.py
> +    def handle_top_level_args(self, parsed_args) -> None:
`parsed_args` has not type.

2021-07-07 03:41 UTC, rt121212121 commented on electrumsv_sdk/validate_cli_args.py
> +    def handle_install_args(self, parsed_args) -> None:
All functions with `parsed_args` argument need the same type.

2021-07-08 02:41 UTC, AustEcon commented on electrumsv_sdk/utils.py
> +        metadata: Dict = component_dict.get("metadata", {})
The component_dict makes sense but not sure if metadata TypedDict makes sense because the whole idea with that was as a dumping ground for miscellaneous configurations on a per-plugin / per-component basis so it would end up having a wide range of Optional types and would need to be updated for new plugin components that get added.. Happy to still do it as long as you understand this trade-off..

2021-07-08 02:48 UTC, AustEcon commented on electrumsv_sdk/utils.py
> +def spawn_new_terminal(command: str, env_vars: Dict, id: str, component_name:
I thought that Dict[str, str] should do fine here so have gone with that.

2021-07-08 02:49 UTC, AustEcon commented on electrumsv_sdk/utils.py
> +        metadata: Dict = component_dict.get("metadata", {})
This is the only remaining thing I have not changed so far in the latest commit - but as I say happy to if you prefer.

2021-07-08 03:08 UTC, AustEcon commented on electrumsv_sdk/builtin_components/electrumsv/electrumsv.py
> +        self.plugin_tools: PluginTools = PluginTools(self, self.config)  # type: ignore
The type: ignore was left by mistake but the reason it needs the : PluginTools type hint is to override the AbstractLocalTools type which does not have all of the methods such as `create_wallet` or `delete_wallet` for electrumsv or in the case of electrumx `run_coroutine_ipython_friendly`... they each have their own local PluginTools instance - it can't really be statically typed because that's now how it was designed.

2021-07-08 03:12 UTC, AustEcon commented on electrumsv_sdk/builtin_components/electrumsv/electrumsv.py
> +        self.plugin_tools: PluginTools = PluginTools(self, self.config)  # type: ignore
Ah! Never mind... If I remove the self.tools field from the `AbstractPluginTools` the issue goes away..

2021-07-09 06:38 UTC, AustEcon commented on electrumsv_sdk/config.py
> +    cli_extension_args: dict = {}
In this case no it needs to be dynamic on a per plugin basis

2021-07-09 07:50 UTC, AustEcon commented on electrumsv_sdk/utils.py
> +def cast_str_int_args_to_int(node_args: List) -> List:
I need to convert from a List[str] to a List[Union[str, int]] but mypy really does not like this... Not sure how else to keep mypy happy for this one

2021-07-15 03:35 UTC, merged